//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginApiApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public System.Guid UserAccountId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int LoginAttempts { get; set; }
        public bool Locked { get; set; }
        public bool IsAdmin { get; set; }
        public bool ConfirmedEmail { get; set; }
        public bool IsAuthorized { get; set; }
        public System.DateTime LastLogin { get; set; }
        public System.DateTime SignupDate { get; set; }
        public System.Guid UserUserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
